import TaecherLoginSceen from "./AllScreens/TeacherLoginScreen/TaecherLoginSceen"
import LoginOptionScreen from "./AllScreens/LoginOptionScreen/LoginOptionScreen"
import TeacherHomeScreen from "./AllScreens/HomeScreen/TeacherHomeScreen"
import ManageCourses from "./AllScreens/ManageCourses/ManageCourses"
import { TeacherProfile } from "./AllScreens/Profile/Profile"
import { ManageAttendance } from "./AllScreens/ManageAttendance/ManageAttendance"
import { MannageMarks } from "./AllScreens/ManageMarks/MannageMarks"
import { Assignment } from "./AllScreens/AssignmentScreen/Assignment"
import { CourseContents } from "./AllScreens/CourseContents/CourseContents"
import { AttendanceOverview } from "./AllScreens/Attendanceoverview/AttendanceOverview"
import { History } from "./AllScreens/History/History"
import { AttendanceHistory } from "./AllScreens/AttendnceHistory/AttendanceHistory"
import { MarksHistory } from "./AllScreens/MarksHistory/MarksHistory"
import { MarksHistoryStudent } from "./AllScreens/MarksHistoryStudent/MarksHistoryStudent"
export {MannageMarks,MarksHistory,AttendanceHistory,MarksHistoryStudent,History,AttendanceOverview,CourseContents,TeacherProfile,TaecherLoginSceen,ManageAttendance, LoginOptionScreen,TeacherHomeScreen,ManageCourses,Assignment}